#!/bin/bash

# Run Dart format

echo
echo "--- formatting code ---"

formatOutput=$(dart format -l 120 lib noted_catalog/lib)

echo "$formatOutput"
echo "--- code formatted ---"
echo

echo "--- analyzing code ---"

# Run Dart analyze and check for errors
if ! analyzeOutput=$(dart analyze); then
    echo "--- commit rejected after analysis ---"
    echo "$analyzeOutput"
    echo
    exit 1
fi

echo "$analyzeOutput"
echo "--- code analyzed ---"
echo

# If we made it this far, the commit is allowed
exit 0
