name: noted_app
description: An app that helps you keep track of the things that you care about.
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  noted_models:
    git:
      url: https://github.com/NotedApp/noted_models.git
      ref: v0.0.13-alpha

  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.6
  equatable: ^2.0.5
  flutter_quill: ^9.2.2
  meta: ^1.9.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  go_router: ^14.1.4
  firebase_auth: ^5.1.0
  get_it: ^7.6.0
  google_sign_in: ^6.1.4
  firebase_analytics: ^11.0.1
  package_info_plus: ^8.0.0
  cloud_firestore: ^5.0.1
  firebase_database: ^11.0.1
  shimmer: ^3.0.0
  firebase_crashlytics: ^4.0.1
  bloc_concurrency: ^0.2.2
  ogp_data_extract: ^0.1.4
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  firebase_core: ^3.1.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  noted_lints:
    git:
      url: https://github.com/NotedApp/noted_lints.git
      ref: v1.0.2

  bloc_test: ^9.1.1
  mocktail: ^1.0.0
  firebase_core_platform_interface: ^5.0.0
  icon_font_generator: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/woman_climbing.svg
    - assets/svg/woman_reading.svg
    - assets/svg/woman_cooking.svg
    - assets/svg/man_computer.svg

  fonts:
    - family: NotedIcons
      fonts:
        - asset: fonts/icons/NotedIcons.otf
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Regular.ttf
        - asset: fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Lora
      fonts:
        - asset: fonts/lora/Lora-Regular.ttf
        - asset: fonts/lora/Lora-Italic.ttf
          style: italic
        - asset: fonts/lora/Lora-Medium.ttf
          weight: 500
        - asset: fonts/lora/Lora-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/lora/Lora-Bold.ttf
          weight: 700
        - asset: fonts/lora/Lora-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Vollkorn
      fonts:
        - asset: fonts/vollkorn/Vollkorn-Regular.ttf
        - asset: fonts/vollkorn/Vollkorn-Italic.ttf
          style: italic
        - asset: fonts/vollkorn/Vollkorn-Medium.ttf
          weight: 500
        - asset: fonts/vollkorn/Vollkorn-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/vollkorn/Vollkorn-Bold.ttf
          weight: 700
        - asset: fonts/vollkorn/Vollkorn-BoldItalic.ttf
          style: italic
          weight: 700
